export const monoNight = {
  'code[class*="language-"]': {
    color: '#e6edf3',
    background: 'transparent',
    fontFamily: '"JetBrains Mono", "SF Mono", Menlo, Consolas, monospace',
    fontSize: '13px',
    lineHeight: '1.65',
    textShadow: 'none',
    tabSize: 2,
  },
  'pre[class*="language-"]': {
    background: 'transparent',
    margin: 0,
    padding: 0,
    overflow: 'auto',
  },
  comment: { color: '#7d8590', fontStyle: 'italic' },
  prolog: { color: '#7d8590' },
  doctype: { color: '#7d8590' },
  cdata: { color: '#7d8590' },
  punctuation: { color: '#b6bfca' },
  property: { color: '#79c0ff' },
  tag: { color: '#7ee787' },
  boolean: { color: '#ff7b72' },
  number: { color: '#79c0ff' },
  constant: { color: '#79c0ff' },
  symbol: { color: '#79c0ff' },
  deleted: { color: '#ff7b72' },
  selector: { color: '#7ee787' },
  'attr-name': { color: '#79c0ff' },
  string: { color: '#a5d6ff' },
  char: { color: '#a5d6ff' },
  builtin: { color: '#ffa657' },
  inserted: { color: '#7ee787' },
  operator: { color: '#ff7b72' },
  entity: { color: '#79c0ff' },
  url: { color: '#a5d6ff' },
  atrule: { color: '#ff7b72' },
  'attr-value': { color: '#a5d6ff' },
  keyword: { color: '#ff7b72', fontWeight: 500 },
  function: { color: '#79c0ff' },
  'function-variable': { color: '#79c0ff' },
  'class-name': { color: '#ffa657' },
  regex: { color: '#7ee787' },
  important: { color: '#ff7b72' },
  variable: { color: '#e6edf3' },
  bold: { fontWeight: 600 },
  italic: { fontStyle: 'italic' },
};
